
[tool.coverage.run]
source = [
    ".",
]
omit = [
    "*/node_modules/*",
] 

[tool.coverage.report]
# make this higher ?
fail_under = 60
show_missing = true
skip_covered = true

[tool.flake8]
exclude = [
    '__pycache__',
    'docker/*',
    'locale/*',
    'media/*',
    'static/*',
    'staticfiles/*',
    'templates/*',
]
ignore =[
    'E128', # visual indents
    'E2',   # whitespaces
    'E3',   # blank lines
    'E701', # multiple statements on a colon line (cleaner single line if branching)
    'E704', # multiple statements on a colon line
    'W293', # blank lint contains whitespace
    'W504', # line break after binary operator
    'W291', # trailing whitespaces
    'W503', # bad practice: PEP 8 recommended style, which was changed on April 16th, 2016
]
max-line-length = 120
show-source = true
builtins = 'self'
count = true
statistics = true


[tool.pyright]
include = ["."]
exclude = ["**/node_modules",
    "**/__pycache__",
    "staticfiles/*",
    "static/*"
]
defineConstant = { DEBUG = true }

reportMissingImports = true
reportMissingTypeStubs = false

pythonVersion = "3.10"
# pythonPlatform = "Linux"
