SELECT
    COLUMN_NAME,
    IS_NULLABLE,
    DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
-- need to add table name filter
-- WHERE TABLE_NAME='FREQ_LONG_MOLLUSQUE'
-- AND IS_NULLABLE='NO'
-- AND (DATA_TYPE='INTEGER' OR DATA_TYPE='DOUBLE PRECISION')